server:
  address: 0.0.0.0
  port: 7000
  servlet:
    encoding:
      force: true
      charset: UTF-8


spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  application:
    name: team-service

  # database
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/diplomacy
    username: postgres
    password: 123456
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 10
      pool-prepared-statements: true
      max-open-prepared-statements: 100

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl









